#pragma once

#include <array>
#include <chrono>
#include <string>
#include <limits>
#include <iostream>


#include <Core/Utils/SpaceUtils.hpp>
#include <Core/Utils/SystemUtils.hpp>
#include <Core/Utils/FilePathUtils.hpp>
#include <Core/Application/IO/LoggingManager.hpp>
#include <Core/Application/Resources/CleanupManager.hpp>
#include <Core/Application/Resources/ServiceLocator.hpp>

#include <Platform/Vulkan/VkSyncManager.hpp>
#include <Platform/Vulkan/VkDeviceManager.hpp>
#include <Platform/Vulkan/VkCommandManager.hpp>
#include <Platform/Vulkan/VkCoreResourcesManager.hpp>
#include <Platform/External/GLM.hpp>
#include <Platform/External/GLFWVulkan.hpp>

#include <Engine/Scene/Camera.hpp>
#include <Engine/Registry/ECS/ECS.hpp>
#include <Engine/Registry/ECS/Components/ModelComponents.hpp>
#include <Engine/Registry/ECS/Components/PhysicsComponents.hpp>
#include <Engine/Registry/ECS/Components/TelemetryComponents.hpp>
#include <Engine/Registry/Event/EventDispatcher.hpp>
#include <Engine/Rendering/Data/Buffer.hpp>
#include <Engine/Rendering/Data/Geometry.hpp>


class VkBufferManager {
public:
    VkBufferManager(VkCoreResourcesManager *coreResources, VkSwapchainManager *swapchainMgr);
    ~VkBufferManager();


    /* Creates a buffer.
        @param &buffer: The buffer to be created.
        @param bufferSize: The size of the buffer (in bytes).
        @param usageFlags: Flags specifying how the buffer will be used.
        @param bufferAllocation: The memory block allocated for the buffer.
        @param bufferAllocationCreateInfo: The buffer allocation create info struct.
        
        @return The cleanup task ID for the newly created buffer.
    */
    static CleanupID CreateBuffer(VkBuffer& buffer, VkDeviceSize bufferSize, VkBufferUsageFlags usageFlags, VmaAllocation& bufferAllocation, VmaAllocationCreateInfo bufferAllocationCreateInfo);

private:
    std::shared_ptr<ECSRegistry> m_ecsRegistry;
    std::shared_ptr<EventDispatcher> m_eventDispatcher;
    std::shared_ptr<CleanupManager> m_cleanupManager;

    std::shared_ptr<Camera> m_camera;

    VmaAllocator m_vmaAllocator;
    QueueFamilyIndices m_queueFamilies;
    VkPhysicalDevice m_physicalDevice;
    VkDevice m_logicalDevice;
    VkPhysicalDeviceProperties m_deviceProperties;
    VkExtent2D m_swapchainExtent;


    // Buffers
    VkBuffer m_vertexBuffer = VK_NULL_HANDLE;
    VmaAllocation m_vertexBufferAllocation = VK_NULL_HANDLE;

    VkBuffer m_indexBuffer = VK_NULL_HANDLE;
    VmaAllocation m_indexBufferAllocation = VK_NULL_HANDLE;

    VkBuffer m_matParamsBuffer = VK_NULL_HANDLE;
    VmaAllocation m_matParamsBufferAllocation = VK_NULL_HANDLE;
    void *m_matParamsBufferMappedData = nullptr;
    size_t m_matStrideSize = 0;

    std::vector<Buffer::BufferAndAlloc> m_globalUBOs;
    std::vector<void*> m_globalUBOMappedData;

    std::vector<Buffer::BufferAndAlloc> m_objectUBOs;
    std::vector<void*> m_objectUBOMappedData;
    size_t m_alignedObjectUBOSize = 0;

    std::vector<VkDescriptorSet> m_perFrameDescriptorSets;
    VkDescriptorSet m_matParamsDescriptorSet;


    // Geometry data
    std::vector<Geometry::Vertex> m_vertices = {};
    std::vector<uint32_t> m_vertIndices = {};
    size_t m_totalObjects = 0;
    Geometry::GeometryData *m_geomData = nullptr;
    Entity m_renderSpace{};


    // Session data
    bool m_sceneInitReady = false;      // Is the scene ready to be initialized?
    CleanupID m_depParentID;            // Virtual task of which real tasks of dependencies are children

        // Viewport data
    glm::vec2 m_uiViewportSceneRegion{};


    void bindEvents();


    /* Continunally checks for event callback statuses to determine whether the buffer manager is initialized.
        @param selfIndex: The buffer manager's subscriber index generated by the event dispatcher.
    */
    void checkForInit(const EventDispatcher::SubscriberIndex &selfIndex);


    /* Copies the contents from a source buffer to a destination buffer.
        @param srcBuffer: The source buffer that stores the contents to be transferred.
        @param dstBuffer: The destination buffer to receive the contents from the source buffer.
        @param deviceSize: The size of either the source or destination buffer (in bytes).
    */
    void copyBuffer(VkBuffer srcBuffer, VkBuffer dstBuffer, VkDeviceSize deviceSize);


    /* Writes data to a buffer that is allocated in GPU (device-local) memory.
        @param data: The data to write to the buffer.
        @param buffer: The buffer to which the data is to be written.
        @param bufferSize: The size of the buffer (in bytes).
    */
    void writeDataToGPUBuffer(const void* data, VkBuffer& buffer, VkDeviceSize bufferSize);


    /* Creates the global vertex buffer. */
    void createGlobalVertexBuffer(const std::vector<Geometry::Vertex> &vertexData);


    /* Creates the global index buffer. */
    void createGlobalIndexBuffer(const std::vector<uint32_t> &indexData);


    /* Creates per-frame uniform buffers. */
    void createPerFrameUniformBuffers();


    /* Creates the PBR material parameters uniform buffer. */
    void createMatParamsUniformBuffer();


    /* Do an initial descriptor set update on the per-frame uniform buffers. */
    void initPerFrameUniformBuffers();


    /* Do an initial descriptor set update on the PBR material parameters uniform buffer. */
    void initMatParamsUniformBuffer();


    /* Updates the global uniform buffer.
        @param currentImage: The index of the current frame.
        @param renderOrigin: The render anchor frame for relative position computations.
    */
    void updateGlobalUBO(uint32_t currentImage, const glm::dvec3 &renderOrigin);


    /* Updates per-object uniform buffers.
        @param currentImage: The index of the current frame.
        @param renderOrigin: The render anchor frame for relative position computations.
    */
    void updateObjectUBOs(uint32_t currentImage, const glm::dvec3 &renderOrigin);


    /* Finds the memory type suitable for buffer and application requirements.
        
        GPUs offer different types of memory to allocate from, each differs in allowed operations and performance characteristics.
	    @param typeFilter: A bitfield specifying the memory types that are suitable.
	    @param properties: The properties of the memory.

	    @return The index of the sutiable memory type.
    */
    uint32_t findMemoryType(uint32_t typeFilter, VkMemoryPropertyFlags properties);
};
